language: python
python:
- '3.3'
- pypy
branches:
  only:
    - master
install:
  - pip install -r requirements_travis.txt
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python deploy/deploy.py; fi'
env:
  global:
    secure: DFb/a0UP1gfLzMJ2c+PEmUnhurND4FzHP0Skh8sWr+AIrg2NULJ2IuAErCNn87/3of4LsGhunmF8d0qtd2zUskds5XJ0HUVOyNximkMv3796NermYXIqiC0Z6v5oZ3UAZknaQ11BBRymQmDbMs375AxtuIyboDs1uij+QOzmcbyaG5ScvBeuzIgMQUhWi5fMCcEmdU0DTJOb/fDFlt4u1e88ulo48lRyuK46vRtjhIS1a4RdhLSamErjgxOtk6GXI1yFB2++Iqun/ffEfZmpACcxd+uedTj3n/I5iqT6YAuvHDe4aqAUah6hxvc9gFGqgNlhNFdM73bvbDrLGt4VfhS5jt6xPdI5FqzU98TlQ/iUvBLC6pubq86+Ph/mvVCv/YMXI/zoizNdxthouqvZ5+VBqEOdf3UV329yqa0wq26pjJ6oPR+Aj6K3DrW+2CqABPUqSd/CLf9KkOUd/doBlYSgGO/QJ7795nZ4sZgYDvvEAP0c6OkssfLrKPMsVgvQTon8J3N08WQC+/OE4M2JeW1C01Sj8V/b58Bbl+K6SoG9cCun+fzsiJtfn7C3Hzpxb8s3zdEFZRGiMbohCr0z4VI+hK/gfiF0Zvw+pRHj9xTgH1swcAn+TM1nLvq3GUXeE4VALkThwKoOUmggNBdZcKWG1Bzzjfbho2BbDk/lEp0=

